```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
```
### 1번
```{r}
e=rnorm(1000)
i=1:1000
t= 2*pi/1000* i
x1 = sin(t)
x2=cos(4*t)
y=1.5+5*x1+3*x2+e
```
```{r}
plot(t,y,col='gray60')
```

```{r}
a=cbind(1,x1,x2)
b=rbind(1.5,5,3)
x4=a%*%b
x4=as.vector(x4)
``` 

```{r}
plot(t,y,col='gray60')
lines(t,x4,col='red',lwd=3)
```

```{r}
x5=solve(t(x4) %*% x4 )%*% t(x4) %*% y
x6= x4 %*% x5
```

```{r}
plot(t,y,col='gray60')
lines(t,x4,col='red',lwd=5)
lines(t,x6,col='blue',lty=2, lwd=5)
```
----

## 2번
#### (1)
```{r}
x=seq(from=-1.96, to=1.96, by=0.01)
y=1/sqrt(2*pi)*exp((-1/2)*x^2)
```

```{r}
plot(x,y,type='l')
```

```{r}
xx=runif(10000)*4-2
yy=runif(10000)*0.35+0.05
plot(xx,yy)
lines(x,y,col='red',lwd=3)
```

```{r}
test=function(xx,yy){
    yy<1/sqrt(2*pi)*exp((-1/2)*xx^2)
}
```

```{r}
print(c(xx[1],yy[1]))
print(1/sqrt(2*pi)*exp((-1/2)*xx[1]^2))
test(xx[1],yy[1])
```

```{r}
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[1],yy[1],col='blue')
points(xx[1],1/sqrt(2*pi)*exp((-1/2)*xx[1]^2),col='red')
```

```{r}
tst=c()
for (i in 1:10000) tst[i] =test(xx[i],yy[i])
```

```{r}
plot(xx,yy,col='grey')
lines(x,y, col='red',lwd=3)
points(xx[tst],yy[tst],col='red')
```

```{r}
sum(tst)
```

```{r}
5503/10000 *0.8
```

#### 답은 0.44024이다

### (2)

```{r}
a=rnorm(1000)
sum((a>-1.96)*(a<1.96))
```

### 3번
 
#### a타입
```{r}
a=0  #아무도 안죽은 경우
a=a+(choose(20,0)*(5^0)*(0.5^(19))*0.95)

#10만 죽은 경우
for(i in 0:19)
{
a=a+((0.5^1)*(0.5^i)*(0.95^(19-i)))
}
#10과 9만 죽은 경우
a=a+(choose(20,2)*(0.5 ^1)*(0.5^(18))*(0.95^1))

print(a*100)
```

#### b타입
```{r}
b=0  #b 타입 
for(i in 0:7)
{
b=b+(choose(20,i)*(0.5^i)*(0.5^(20-i)))
}
print(b*100)
``` 

#### a타입이 살 확률이 더 높다



### 4번
```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
```

```{r}
library(tidyverse)
a=as_tibble(df)
```
#### 1번
```{r}
a %>% filter(year==2020) %>% summarise(sum_=sum(cases))
```
#### 2020년의 확진자는 60726이다

```{r}
a %>% filter(year==2021) %>% summarise(sum_=sum(cases))
```

#### 2021 확진자의 총합은 396886이다

### 2번 
```{r}
a %>% filter(year==2020,month==2) %>% filter(day>=1 &day<=15) %>% group_by(prov) %>% summarise(sum_cases=sum(cases))
```


#### 경기가 가장 많다. 
```{r}
a %>% filter(year==2020,month==2) %>% filter(day>=15 & day<=29) %>% group_by(prov) %>% summarise(sum_cases=sum(cases))
```
#### 대구가 가장많다. 
