```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#hide
#options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)
library(tidyverse)
```

## 1번

### 1-(1)

```{r}
epsilon=rnorm(1:1000)
head(epsilon)
```

### 1-(2)

```{r}
i=c(1:1000)
t_i=2*pi*i/1000
```

```{r}
x_1=(sin(t_i))
x_2=(cos(4*(t_i)))
```

```{r}
head(x_1)
head(x_2)
```

### 1-(3)

```{r}
y_i=1.5+5*(x_1)+3*(x_2)+epsilon
```

```{r}
plot(t_i,y_i,col='gray60')
```

### 1-(4)

```{r}
X=cbind(1,x_1,x_2)
head(X)
```

```{r}
dim(X)
```

### 1-(5)

```{r}
Beta=rbind(1.5,5,3)
Beta
```

```{r}
B= X %*% Beta
```

```{r}
B=c(B)
```

```{r}
plot(t_i,y_i,col='gray60')
lines(t_i,B,col='red',lwd=3)
```

### 1-(6)

```{r}
solve(t(X) %*% X)
```

```{r}
t(X)
```

```{r}
y=cbind(y_i)
head(y)
```

```{r}
B_hat = (solve(t(X) %*% X)) %*% t(X) %*% y
B_hat
```

### 1-(7)
```{r}
XB_hat=X %*% B_hat
head(XB_hat)
```

```{r}
plot(t_i,y_i,col='gray60')
lines(t_i,B,col='red',lwd=3)
lines(t_i,XB_hat,col='blue',lwd=3,lty=2)
```

\newpage

## 2번

### 2-(1)

```{r}
x=seq(from=-1.96,to=1.96,by=0.01)
y=(1/sqrt(2*pi)*exp(-0.5*(x^2)))
```

```{r}
plot(x,y,type='l')
```

```{r}
xx=runif(10000)
xx=xx*4-2

yy=runif(10000)*0.4
```

```{r}
plot(xx,yy)
lines(x,y,col='red',lwd=3)
```

```{r}
test = function(xx,yy){
    yy < (1/sqrt(2*pi))*exp((-1/2)*(xx**2))
}
```

```{r}
print(c(xx[1],yy[1]))
print(1/sqrt(2*pi))*exp((-1/2)*(xx[1]**2))
test(xx[1],yy[1])
```

```{r}
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[1],yy[1],col='blue')
points(xx[1],1/sqrt(2*pi)*exp(-0.5*(xx[1]^2)),col='red')
```

```{r}
tst=c()
for (i in 1:10000) tst[i]=test(xx[i],yy[i])
```

```{r}
head(tst)
```

```{r}
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[tst],yy[tst],col='red')
```

```{r}
sum_tst=sum(tst)
sum_tst
```

```{r}
w=0.4*4
```

```{r}
sum_tst/10000*w
```

### 2-(2)

```{r}
P=rnorm(1:1000)
```

```{r}
length(which((P<=1.96)&P>=-1.96))
```

\newpage

## 3번

**Type A**

```{r}
A_1 = sum(rbinom(1000,size=20,p=0.95)==19)
A_1
```

```{r}
A_2 = sum(rbinom(1000,size=1,p=0.5)==1)
A_2
```

```{r}
A_1 + A_2
```

**Type B**

```{r}
B_1 = sum(rbinom(1000,size=20,p=0.5)==8)
B_1
```

```{r}
B_2 = sum(rbinom(1000,size=12,p=0.95)==12)
B_2
```

```{r}
B_1 + B_2
```

- 따라서 Type A의 경우에 8번 참가자가 살아남을 가능성이 더 높다.

\newpage

## 4번 


```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)
```

### 4-(1)

```{r}
A=df %>% filter(year==2020) %>% select(cases)
head(A)
```

```{r}
sum(A)
```

- sum(A)는 2020년의 확진자 수 총합이다.

```{r}
B=df %>% filter(year==2021) %>% select(cases)
head(B)
```

```{r}
sum(B)
```

- sum(B)는 2021년의 확진자 수 총합이다.

### 4-(2)

```{r}
df %>% group_by(prov) %>% filter (year==2020 & month==2 & day<16)  %>% summarise(cases_sum=sum(cases))
```

- 주어진 기간동안 가장 많은 확진자가 나온 지역은 '경기'이다.

### 4-(3)

```{r}
df %>% group_by(prov) %>% filter (year==2020 & month==2 & day<30 & day>15) %>% summarise(cases_sum=sum(cases))
```

- 주어진 기간동안 가장 많은 확진자가 나온 지역은 '대구'이다.
