---
title: "Untitled"
author: "김재승"
date: '2021 12 21 '
output: 
  pdf_document:
    latex_engine: xelatex
---

## 회귀분석
#(1)
```{r}
e = rnorm(1000)

#(2)
t = 1:1000*2*pi/1000
x1 = sin(t)
x2 = cos(4*t)

#(3)
y = 1.5+5*x1+3*x2+e
X = cbind(x1,x2)
plot(t,y,col="gray60")

#(4)
X = cbind(rep(1,1000),x1,x2)

#(5)
B = cbind(c(1.5,5,3))
V = as.vector(X %*% B)
lines(t,V,col="red",lwd=4)

#(6)
y_ = cbind(y)
B_ = (solve(t(X) %*% X) %*% t(X) %*% y_)
B
B_

#(7)
V_ = as.vector(X %*% B_)
lines(t,V_,col="blue",lty="dashed",lwd=4)
```

##몬테카를로 적분
#(1)
```{r}
x = runif(5000,0,1.96)
y = runif(5000,0,0.5)
plot(x,y)
lines(x, exp(-x**2/2)/(2*pi)**0.5,col='red')
a = sum(y <=  exp(-x**2/2)/(2*pi)**0.5)
(a/5000)*0.5*1.96*2
```

#(2)
```{r}
x = rnorm(1000)
sum(x >= -1.96 & x <= 1.96)
```

##징검다리
```{r}
# TYPE A
x = rbinom(1000,20,0.5)
sum(x >= 13) / 1000
```

```{r warning = FALSE, message = FALSE}
# TYPE B
x=c()
for(i in 1:1000){
  a = rbinom(20,1,0.5)
  b = rbinom(20,1,0.95)
  c = rbinom(20,1,0.5)
  x[i] = min(which(a==0)) + 
  min(which(b==0)) + min(which(c==0))
}
1-sum(x<=20)/1000
```
# Type B의 경우가 살아남을 확률이 높다

library(tidyverse)
##COVID19
```{r}
library(tidyverse)
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)

#(1)
a = df %>% filter(df$year == 2020)
sum(a$cases)
b = df %>% filter(df$year == 2021)
sum(a$cases)

#(2)
a1 = a %>% filter(a$month == 2 & day >=1 & day <=15)
max(a1$prov)

#(3)
a2 = a %>% filter(a$month == 2 & day >=16 & day <=29)
max(a2$prov)
```
