## 1번 문제풀이
```{r}
#1
epsilon = rnorm(1000)
head(epsilon)
#2
i = (1:1000)
t <- (2*pi*i)/1000
X1 = sin(t)
X2 = cos(4*t)
head(X1)
head(X2)
#3
y <- 1.5+(5*X1)+(3*X2)+epsilon
plot(t,y,col='gray60')
```
```{r}
#4
a_ <- c()
for (i in 1:1000){
  a_[i]<- 1
}
X = cbind(a_,X1,X2)
head(X)
#5
Beta = rbind(1.5,5,3)
XB=X %*% Beta
XBv = as.vector(XB)
head(XBv)
plot(t,y,col='gray60')
lines(t,XBv,col='red',lwd='3')
```
```{r}
#6
Bh = solve(t(X) %*% X) %*% t(X) %*% y
Bh
Beta
#7
XBh = X %*% Bh
XBhv = as.vector(XBh)
head(XBhv)
plot(t,y,col='gray60')
lines(t,XBv,col='red',lwd='3')
lines(t,XBhv,lty=2,col='blue',lwd= '3')


```

\newpage
## 2번 문제풀이
```{r}
#1
x = seq(-1.96,1.96,0.01)
y = (1/sqrt(2*pi))*exp((-(x^2))/2)
plot(x,y)
```
```{r}
xx = runif(n=10000,-2,2)
yy = runif(n=10000,0.05,0.4)
plot(xx,yy)
lines(x,y,col='red',lwd=3)
```
```{r}
test = function(xx,yy){
    yy < (1/sqrt(2*pi))*exp((-(xx^2))/2)
}
print(c(xx[1],yy[1])) 
print(1/sqrt(2*pi))*exp((-(xx[1]^2))/2) 
test(xx[1],yy[1])

plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[1],yy[1],col='blue')
points(xx[1],(1/sqrt(2*pi))*exp((-(xx[1]^2))/2),col='red')
```
```{r}
tst = c()
for (i in 1:10000) tst[i] = test(xx[i],yy[i])
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[tst],yy[tst],col='red')
sum(tst)
#10000개 중에서 5406개가 붉은점 따라서 5406/10000 * 1.4
#(-2에서 2까지 4, 0.05에서0.4까지 0.35, 4*0.35=1.4)

5406/10000*1.4 #약 0.75가 나온다
```
```{r}
#2
library(tidyverse)
x_ <- rnorm(1000)
```
```{r}
dim(x_) = c(1000,1)
x_ = as.tibble(x_)
x__ = x_ %>% filter(1.96 > V1 & -1.96 < x_)
dim(x__) #남은 행의 개수가 구간사이에 있는 확률변수의 개수이다. 
```
\newpage
## 3번 문제풀이
```{r}
# Type A 
#10번의 성공 확률을 제외해도 9번이 19번 건너면 9번 8번 모두 살수있다.
#9번이 19번 성공하는 것 말고도 10번의 성공확률 8번의 성공확률이 있지만
#그것을 제외하고 계산해도 Type B의 확률보다 높다.
A = 0.95^19 #9번 혼자 건너가는 확률
x_ = rbinom(19,size=1,0.95)
#cumprod(x_)
x=sum(cumprod(x_))
xx_ = 19-x-1 
y = rbinom(1, size=xx_, 0.5)
rslt <- c()
for (i in 1:10000){
    x=sum(cumprod(rbinom(19,size=1,0.95)))
    xx_=19-x-1 
    if (xx_>0) y = rbinom(1, size=xx_, 0.5) else y=0 
    rslt[i]=x+y-10
}
mean(rslt)
# 평균 5명이 살아남는다 

#Type B 
#8번이 살기 위해서는 일반인 8명이서 끝까지 건너야한다 
B=0.5^20
mean(rbinom(100000,20,0.5))
#하지만 일반인이 20개의다리를 건너기 위해서는 평균 10명이 필요하다

A>B# True가 나옴으로 9번혼자 건널 때 성공 확률이 더크다고 볼수있다


```

\newpage
## 4번 문제풀이
```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)
```
```{r}
#1
sum(df %>% filter(year==2020) %>% select(cases))#2020 cases
sum(df %>% filter(year==2021) %>% select(cases))#2021 cases
#2
df1 = df %>% filter(year==2020 & month==2 & day<=15)
df1%>% group_by(prov) %>% summarise(sum = sum(cases))
#경기가 9명으로 제일 많다.
```
```{r}
#3
df2 = df %>% filter(year==2020 & month==2 & day>=16)
df2 %>% group_by(prov) %>% summarise(sum = sum(cases))
#대구가 2055명으로 제일 많다.
```
```{r}
```