---
title: "R입문 기말고사"
author: "202016052 김하늘"
date: '2021 12 21 '
output:
  pdf_document:
    includes:
      in_header: head.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("tidyverse")
```

## 1번. 회귀분석 
 
### (1)

 
```{r}
epsilon = rnorm(1000)
head(epsilon)
```


### (2)


```{r}
x1 = c()
x2 = c()

i= 1:1000

t = 2*pi*i/1000

x1[i] = sin(t[i])
x2[i] = cos(4*t[i])
```


### (3)


```{r}
y = c()
for(i in 1:1000){
y[i] = 1.5 + (5*x1[i]) + (3*x2[i]) + epsilon[i]
}

plot(t,y, col='gray60')
```


### (4)


```{r}
X = cbind(1, x1, x2)
dim(X) = c(1000, 3)

head(X)
```


### (5)


```{r}
beta = rbind(1.5, 5, 3)

XB = X%*%beta 
plot(t,y, col='gray60')
lines(t,XB, col='red', lwd=3)
```


### (6)


```{r}
dim(y) = c(1000,1)

X_t = t(X)
XtX_in =solve(X_t%*%X)

B_hat = XtX_in %*% X_t %*% y

B_hat
beta
```


### (7)


```{r}
XB_hat = c()
XB_hat <- X %*% B_hat

plot(t,y, col='gray60')
lines(t,XB, col='red', lwd=3)
lines(t, XB_hat, col='blue', lty=2, lwd=3)
```


## 2번. 몬테카를로 적분


### (1)


```{r}
x=seq(from=-1.96, to=1.96, by=0.01)
y=(1/sqrt(2*pi))*exp(-1*x^2/2)

plot(x,y)
```
```{r}
xx = runif(n=10000, min=-1.96, max=1.96)
yy = runif(n=10000, min=0, max=1/sqrt(2*pi))

plot(xx,yy, col='gray')
lines(x,y, col='red', lwd=2)
```
```{r}
test= function(xx,yy){
yy<(1/sqrt(2*pi))*exp(-1*xx^2/2)
}

tst=c()
for(i in 1:10000){
  tst[i]= test(xx[i], yy[i])
}

plot(xx,yy, col='gray')
lines(x,y, col='red', lwd=2)
points(xx[tst], yy[tst], col='red')
```
```{r}
1/sqrt(2*pi)*3.92*sum(test(xx,yy))/10000
```


### (2)


```{r}
x= rnorm(1000)
sum(-1.96<x & x<1.96)
```

## 3. 징검다리


```{r}
#변수 선언 
arr= c('N1','N2','N3','N4','N5','N6','N7','N8','A9','N10')
surv = 10
stage = 0
player = arr[surv]
p=0.5
toss_rslt = NA
```

```{r}
#함수
toss = function(p){
  if(surv>=1){as.logical(rbinom(n=1, size=1, prob=p))
    }else{TRUE}
    }

reset= function(){
    toss_rslt <<- NA
    surv <<- 10
    stage <<- 0
    player <<- arr[surv]
    }

record = function(){
    list(toss_rslt=toss_rslt, surv=surv, stage=stage, player=player)}

go = function(){
    prob <<- 0.5+ (player=='A9')*0.45
    toss_rslt <<- toss(prob)
    if(surv>=1){
        if(toss_rslt==FALSE){
            surv <<- surv-1
            stage <<- stage+1
            player<<- arr[surv]
        }
    }else if(surv==0){
        toss_rslt <<- NA
        surv <<- 0
        stage <<- stage
        player <<- NA
        }
}

gogo = function(){
  for(i in 1:20) go()
}
```

```{r}
reset()
gogo()
record()
```

```{r}
simulate_once = function(){
    reset()
    gogo()
    return(record()$surv)
    }
simulate_once()
```


### (Type A)


```{r}
sim_rslt = c()
for(i in 1:1000){
  sim_rslt[i] = simulate_once()
}

sum(sim_rslt>=8)/1000 
```

### (Type B)


```{r}
arr=rev(arr)

sim_rslt = c()
for(i in 1:1000){
  sim_rslt[i] = simulate_once()
}

sum(sim_rslt>=3)/1000
```
8번 참가자는 Type A일때 생존확률이 더 높다. 

## 4번. COVID19


```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)
```


### (1)


```{r}
sumc = df %>% group_by(year) %>% summarise(sum(cases))
sumc

list = list(sumc$`sum(cases)`[1], sumc$`sum(cases)`[2])
names(list) <- c('2020년 확진자 총합', '2021년 확진자 총합')
list
```


### (2)


```{r}
summa <- df %>% filter(year==2020 & month==2 & day>=1 & day<=15) %>% group_by(prov) %>% summarise(sum(cases)) 

summa$prov[summa$`sum(cases)`==max(summa$`sum(cases)`)]
```
경기지역이 가장 많다.



### (3)


```{r}
summs = df %>% filter(year==2020 & month==2 & day>=16 & day<=29) %>% group_by(prov) %>% summarise(sum(cases))

summs$prov[summs$`sum(cases)`==max(summs$`sum(cases)`)]
```
대구지역이 가장 많다.