```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.회귀분석 (35점)

### 1-(1)

```{r}
a<-c(rnorm(1000))
head(a)
```

### 1-(2)

```{r}
T<-function(x){
  p=(2*pi*x)/1000
  p
}
x1<-c()
for (i in 1:1000){
  x1[i]<-sin(T(i))
  x1
}
x2<-c()
for (i in 1:1000){
  x2[i]<-cos(4*T(i))
  x2
}
head(x1)
head(x2)
```

### 1-(3)

```{r}
y<-c()
for (i in 1:1000){
  y[i]<-1.5+5*x1[i]+3*x2[i]+a[i]
  y
}

b<-c()
for (i in 1:1000){
  b[i]<-T(i)
  b
}

head(y)
head(b)
plot(b,y,col='gray60')
```

### 1-(4)

```{r}
X=cbind(1,x1,x2)
head(X)
```

### 1-(5)

```{r}
B<-rbind(1.5,5,3)
B
vec<-c(X%*%B)
head(vec)
plot(b,y,col='gray60')
lines(b,vec,col='red',lty=1,lwd=5)
```

### 1-(6)

```{r}
XT<-t(X)
head(y1<-cbind(y))
B_hat=solve(XT%*%X)%*%XT%*%y1
B_hat
B
```

### 1-(7)

```{r}
vec_2<-c(X%*%B_hat)
plot(b,y,col='gray60')
lines(b,vec,col='red',lty=1,lwd=5)
lines(b,vec_2,col='blue',lty=2,lwd=5)
```

\newpage

## 2.몬테카를로 적분 (10점)

### 2-(1)

```{r}
x=seq(from=-1.96,to=1.96,by=0.01)
y=1/sqrt(2*pi)*(exp(1)^(-x^2/2))
plot(x,y)
xx=runif(n=10000,min=-2,max=2)
yy=runif(10000)*0.4
plot(xx,yy)
lines(x,y,col='red',lwd=3)
test = function(xx,yy){
  yy<1/sqrt(2*pi)*(exp(1)^(-xx^2/2))
}
print(c(xx[1],yy[1]))
print(1/sqrt(2*pi)*(exp(1)^(-xx[1]^2/2)))
test(xx[1],yy[1])
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[1],yy[1],col='blue')
points(xx[1],1/sqrt(2*pi)*(exp(1)^(-xx[1]^2/2)),col='red')
tst = c()
for (i in 1:10000){
  tst[i]=test(xx[i],yy[i])
}
head(tst)
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[tst],yy[tst],col='red')
print(sum(tst)/10000*1.6)
```

### 2-(2)

```{r}
a=c(rnorm(1000))
sum(a>-1.96&a<1.96)
```

\newpage

## 3.징검다리(10점)

```{r}
library(tidyverse)
ARR = c('N1','N2','N3','N4','N5','N6','N7','N8','N9','N10')
SURV=10
PLAYER=ARR[SURV]
STAGE=0
PROB=0.5
TOSSRSLT=NA

toss = function(p) rbinom(n=1,size=1,prob=p)%>%as.logical
reset <- function(){
    TOSSRSLT <<- NA
    SURV <<- 10
    STAGE <<- 0
    PLAYER <<- ARR[SURV]
}
reset()
record = function(){
    list(PRE_TOSSRSLT=TOSSRSLT,SURV=SURV,STAGE=STAGE,PLAYER=PLAYER)
}
go = function(){
    if (SURV>0){
        PROB<<-0.5+ (PLAYER=='N9')*0.45
        TOSSRSLT <<- toss(PROB)
        if (TOSSRSLT==FALSE){
            SURV <<- SURV-1
        }
    }else{
        SURV=1
    }
    STAGE <<- STAGE + 1
    PLAYER <<- ARR[SURV]
}

gogo = function() for(i in 1:20) go()

gogo_history = function(){
    rslt_=as_tibble(record())
    for(i in 1:20){
        go()
        rslt_=rbind(rslt_, as_tibble(record()))
    }
    print(rslt_)
}

gogo_history()

simulate_once = function(){
    reset()
    gogo()
    return(record()$SURV)
}
simulate_once()

simrslt = c()
for (i in 1:1000) simrslt[i] = simulate_once()
mean(simrslt) #Type A일경우의 평균 생존 인원 수

ARR = c('N10','N9','N8','N7','N6','N5','N4','N3','N2','N1')
SURV=10
PLAYER=ARR[SURV]
STAGE=0
PROB=0.5
TOSSRSLT=NA

toss = function(p) rbinom(n=1,size=1,prob=p)%>%as.logical
reset <- function(){
    TOSSRSLT <<- NA
    SURV <<- 10
    STAGE <<- 0
    PLAYER <<- ARR[SURV]
}
reset()
record = function(){
    list(PRE_TOSSRSLT=TOSSRSLT,SURV=SURV,STAGE=STAGE,PLAYER=PLAYER)
}
go = function(){
    if (SURV>0){
        PROB<<-0.5+ (PLAYER=='N9')*0.45
        TOSSRSLT <<- toss(PROB)
        if (TOSSRSLT==FALSE){
            SURV <<- SURV-1
        }
    }else{
        SURV=1
    }
    STAGE <<- STAGE + 1
    PLAYER <<- ARR[SURV]
}

gogo = function() for(i in 1:20) go()

gogo_history = function(){
    rslt_=as_tibble(record())
    for(i in 1:20){
        go()
        rslt_=rbind(rslt_, as_tibble(record()))
    }
    print(rslt_)
}

gogo_history()

simulate_once = function(){
    reset()
    gogo()
    return(record()$SURV)
}
simulate_once()

simrslt = c()
for (i in 1:1000) simrslt[i] = simulate_once()
mean(simrslt) #Type B일 경우 평균 생존 인원수
#Type A일 경우의 평균 생존 인원수가 Type B일 경우의 평균 생존 인원수보다 크므로 Type A일
#경우가 8번 참가자가 살아남을 확률이 더 높다.
```

\newpage

## 4.COVID19 (15점)

### 4-(1)

```{r}
library(tidyverse)
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)

df%>%group_by(year)%>%summarize(sum_cases=sum(cases))
#2020년 코로나 확진자 총합=60726
#2021년 코로나 확진자 총합=396886
```

### 4-(2)

```{r}
df%>%filter(df[1]==2020&df[2]==2&df[3]<=15)%>%group_by(prov)%>%summarise(sum_cases=sum(cases))

# 경기지역에서 가장 많은 확진자가 발생했다.
```

### 4-(3)

```{r}
df%>%filter(df[1]==2020&df[2]==2&df[3]>=16&df[3]<=29)%>%group_by(prov)%>%summarise(sum_cases=sum(cases))
# 대구에서 가장 많은 확진자가 발생했다.
```