---
title: "exam"
author: "202121225 í†µê³„í•™ê³¼ ì„œí•˜ì§„"
date: "12/21/2021"
output: pdf_document
---

###1-1

```{r}
i<-1:1000


epsilon_i<-rnorm(n=1000,mean=0,sd=1)

```

###1-2

```{r}
i<-1:1000
t_i<- {2*pi*i}/{1000}
x1<- sin(t_i)
x2<- cos(4*t_i)
```

###1-3

```{r}
i<-1:1000

t_i<- {2*pi*i}/{1000}

x1<- sin(t_i)
x2<- cos(4*t_i)

y_i<- 1.5 + 5*x1 + 3*x2 + epsilon_i

plot(t_i, y_i, col='gray60')
```


###1-4

```{r}
i<-1:1000

t_i<- {2*pi*i}/{1000}

x1<- sin(t_i)
x2<- cos(4*t_i)

X=cbind(1,x1,x2)
```


###1-5

```{r}
ğœ·=cbind(c(1.5,5,3))
Xğœ· <- X%*%ğœ·

plot(t_i, y_i, col='gray60')
lines(t_i,Xğœ· , col="red",lwd='5')
```


###1-6


```{r}
X_t<-t(X)
XtX_ <- solve(X_t%*%X)

hatğœ·= XtX_%*%X_t%*%y_i
hatğœ·
```


###1-7


```{r}
X_hatğœ·<- X%*%hatğœ·

plot(t_i, y_i, col='gray60')
lines(t_i,Xğœ· , col="red",lwd='5')
lines(t_i,X_hatğœ· , lty="dashed", col="blue",lwd='5')

```


###2-1

```{r}
x=seq(from=-1.96,to=1.96,by=0.01)
y=(1/sqrt(2*pi))*exp(-x^2/2)

xx=runif(10000)*4-2
yy=runif(10000)
plot(xx,yy)
lines(x,y,col='red',lwd=3)

test = function(xx,yy){
    yy < (1/sqrt(2*pi))*exp(-xx^2/2)
}

print(c(xx[1],yy[1])) 
print((1/sqrt(2*pi))*exp(-xx[1]^2/2))
test(xx[1],yy[1])

plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[1],yy[1],col='blue')
points(xx[1],(1/sqrt(2*pi))*exp(-xx[1]^2/2),col='red')

tst = c()
for (i in 1:10000) tst[i] = test(xx[i],yy[i])
head(tst)

plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=3)
points(xx[tst],yy[tst],col='red')


sum(tst)/10000*4



```


###2-2

```{r}

library(tidyverse)

x<-rnorm(1000)
dim(x)=c(1000,1)
x= as_tibble(x)
x %>% filter(V1>-1.96&V1<1.96)

```


###3

TYPE A


###4


```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')


###(1)

df%>%filter(year==2020) %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021) %>%summarise(sum_cases=sum(cases))


###(2)

df%>%filter(year==2021 &month==2 &day<16 &prov=="ì„œìš¸") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ë¶€ì‚°") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ëŒ€êµ¬") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì¸ì²œ") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ê´‘ì£¼") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ëŒ€ì „") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ìš¸ì‚°") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì„¸ì¢…") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ê²½ê¸°") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ê°•ì›") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì¶©ë¶") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì¶©ë‚¨") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì „ë¶") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì „ë‚¨") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ê²½ë¶") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ê²½ë‚¨") %>%summarise(sum_cases=sum(cases))
df%>%filter(year==2021 &month==2 &day<16 &prov=="ì œì£¼") %>%summarise(sum_cases=sum(cases))

##ë‹µ : ì„œìš¸

###(3)

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì„œìš¸") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ë¶€ì‚°") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ëŒ€êµ¬") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì¸ì²œ") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ê´‘ì£¼") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ëŒ€ì „") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ìš¸ì‚°") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì„¸ì¢…") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ê²½ê¸°") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ê°•ì›") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì¶©ë¶") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì¶©ë‚¨") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì „ë¶") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì „ë‚¨") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ê²½ë¶") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ê²½ë‚¨") %>%summarise(sum_cases=sum(cases))

df%>%filter(year==2021 &month==2 &(day>15&day<30) &prov=="ì œì£¼") %>%summarise(sum_cases=sum(cases))


##ë‹µ : ê²½ê¸°

```


