---
title: "R 기말고사 예상문제"
author: "오동운(202115809)"
output:
  pdf_document:
    includes:
      in_header: head.tex
---
```{r}
library(dplyr)
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1-1
```{r}
epsilon <- rnorm(1000)
head(epsilon)
```

## 1-2
```{r}
x1<-c()
x2<-c()
t<-c()
for(i in 1:1000){
  t[i] <- 2*pi*i/1000
}
for(i in 1:1000){
  x1[i] <- sin(t[i])
  x2[i] <- cos(4*t[i])
}

head(x1)

head(x2)
```

\newpage
## 1-3
```{r}
y<-c()
for(i in 1:1000){
  y[i] <- 1.5 + 5*x1[i] + 3*x2[i] + epsilon[i]
}
plot(t,y,col='gray60')
```

## 1-4
```{r}
X <- cbind(1,x1,x2)
head(X)
```


## 1-5

```{r}
beta = rbind(1.5,5,3)
beta

XP1 = X %*% beta

plot(t,y,col='gray60')
lines(t,XP1,col='red',lwd='3')
```

\newpage
## 1-6
```{r}
beta
beta2 = solve(t(X) %*% X )%*%t(X)%*%y
beta2
```


## 1-7
```{r}
XP2 <- X %*% beta2
plot(t,y,col='gray60')
lines(t,XP1,col='red',lwd=4)
lines(t,XP2,col='blue',lty= 2,lwd=5)
```



\newpage
## 2-1
```{r}
x = seq(from=0, to=2, by=0.01)
y = (2*exp(-1/2*x^2))/(2*pi)^(1/2)

plot(x,y)

xx = runif(n=10000,min=0,max=2)
yy = runif(n=10000,min=0,max=1)

plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=5)

test<-function(xx,yy){
  yy < (2*exp(-1/2*xx^2)) /(2*pi)^(1/2)
}

tst<-c()
for(i in 1:10000){
  tst[i] <- test(xx[i],yy[i])
}

plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=5)
points(xx[tst],yy[tst],col='red')

sum(tst)
```

\newpage
## 2-2
```{r}

A = rnorm(1000)
sum(abs(A) < 1.96)

```

\newpage
## 4-1
```{r}
df=read.csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv',fileEncoding = "utf-8")
head(df)

A = df %>% filter(year==2020)



A %>% select(5) %>% sum

B = df %>% filter(year==2021)


B %>% select(5) %>% sum


```
\newpage
## 4-2
```{r}
DF = df %>% filter(year==2020 & month == 2 & day<=15)
DF %>% group_by(prov) %>% summarise(sum_cases = sum(cases))


"경기이다."

```
\newpage
## 4-3
```{r}
DF2 = df %>% filter(year==2020 & month == 2 & day%in%c(16:29))
DF2 %>% group_by(prov) %>% summarise(sum_cases = sum(cases))


"대구이다."

```


























