---
title: "R 입문 기말고사"
author: "이태관(202121238)"
date: "12/21/2021"
fontsize: 12pt ##10,11,12
output: 
  pdf_document:
    includes:
      in_header: head.tex
---

## 1번

```{r}
##(1)
e = rnorm(1000)
##(2)
t = c()
x_1 = c()
x_2 = c()
y = c()
for(i in 1:1000) t[i] = ((2*pi*i)/1000)
for(i in 1:1000) x_1[i] = sin(t[i])
for(i in 1:1000) x_2[i] = cos(4*t[i])


##(3)
for(i in 1:1000) y[i] = 1.5 + 5*x_1[i] + 3*x_2[i] + e[i]
plot(t,y,col='gray60')


##(4)
X = cbind(1,x_1,x_2)
head(X)


##(5)
B = rbind(1.5,5,3)
V = as.vector(X %*% B)
head(V)
lines(t,V,col='red', lwd=5)



##(6)
b_h = solve(t(X) %*% X) %*% t(X) %*% y
print(B)
print(b_h)
## 둘이 거의 동일함을 알 수 있다.


##(7)
V_2 = as.vector(X %*% b_h)
head(V_2)
lines(t,V_2,col='blue', lwd=3, lty="dashed")
```

## 2번
```{r}
library(tidyverse)
##(1)
x=seq(from=-1.96,to=1.96, by=0.01)
y_1= (1/sqrt(2*pi))*exp((-1/2)*(x^2))
x_one = runif(5000)*-2
x_two = runif(5000)*2
xx = c(x_one,x_two)
yy = runif(10000)*(0.4)
plot(xx,yy)
lines(x,y_1,col='red', lwd=3)
test = function(xx,yy){
  yy < abs(1/sqrt(2*pi))*exp((-1/2)*(xx^2))
}
print(c(xx[1],yy[1]))
test(xx[1],yy[1])
tst = c()
##제대로 작동한다.

for (i in 1:10000) tst[i] = test(xx[i],yy[i])
points(xx[tst],yy[tst],col='red')
sum(tst) 
sum(tst)/10000 * 1.6 
## 약 0.95임을 알 수 있다.


##(2)
rndm = rnorm(1000)
rndm = as_tibble(rndm)
colnames(rndm) = c('X1')
rndm %>% filter(X1>-1.96 & X1<1.96) %>% count
##약 940~950개가 있음을 알 수 있다.

```

### 3번
```{r}
##Type A
library(tidyverse)
ARR = c('N1','N2','N3','N4','N5','N6','N7','N8','PRO','N9')
SURV = 10
PLAYER = ARR[SURV]
STAGE = 0
PROB = 0.5
TOSSRSLT = NA
toss = function(p) rbinom(n=1, size=1, prob=p) %>% as.logical
reset = function(){
  TOSSRSLT <<- NA
  SURV <<- 10
  STAGE <<- 0
  PLAYER <<- ARR[SURV]
}
record = function(){
  list(PRE_TOSSRSLT=TOSSRSLT, SURV=SURV, STAGE=STAGE, PLAYER=PLAYER)
}
go = function(){
  if(SURV == 0){
  return()
  }
  PROB <<- 0.5+ (PLAYER=='PRO')*0.45
  TOSSRSLT <<- toss(PROB)
  if(TOSSRSLT==FALSE) SURV <<- SURV - 1
  STAGE <<- STAGE + 1
  PLAYER <<- ARR[SURV]
}

gogo = function() for(i in 1:20) go()


simulate_once = function(){
  reset()
  gogo()
  return(record()$SURV)
}

simrslt = c()
for(i in 1:10000) simrslt[i] = simulate_once()
mean(simrslt)
sum(simrslt>=8) ## 생존자가 8명 이상이어야 8번이 산다.

## Type B
library(tidyverse)
ARR = c('N9','PRO','N8','N7','N6','N5','N4','N3','N2','N1')
SURV = 10
PLAYER = ARR[SURV]
STAGE = 0
PROB = 0.5
TOSSRSLT = NA
toss = function(p) rbinom(n=1, size=1, prob=p) %>% as.logical
reset = function(){
  TOSSRSLT <<- NA
  SURV <<- 10
  STAGE <<- 0
  PLAYER <<- ARR[SURV]
}
record = function(){
  list(PRE_TOSSRSLT=TOSSRSLT, SURV=SURV, STAGE=STAGE, PLAYER=PLAYER)
}
go = function(){
  if(SURV == 0){
  return() ##생존자가 0명이 될 경우 go를 거치지 않고 반환
  }
  PROB <<- 0.5+ (PLAYER=='PRO')*0.45
  TOSSRSLT <<- toss(PROB)
  if(TOSSRSLT==FALSE) SURV <<- SURV - 1
  STAGE <<- STAGE + 1
  PLAYER <<- ARR[SURV]
}

gogo = function() for(i in 1:20) go()


simulate_once = function(){
  reset()
  gogo()
  return(record()$SURV)
}

simrslt = c()
for(i in 1:10000) simrslt[i] = simulate_once()
mean(simrslt)
sum(simrslt>=3) ##생존자가 3명 이상이면 8번이 살아남은 것이다.

## Type A 의 경우가 8번 생존자가 더 많이 살아남을 수 있다.
```


### 4번
```{r}
library(tidyverse)
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)
##(1)
df %>% 
group_by(year) %>%
summarise(confirm = sum(cases))


##(2)
df %>% 
filter(year == 2020 & month ==2 & day < 16 )%>%
group_by(prov) %>% 
summarise(confirm = sum(cases))
##경기에서 가장 많이 발생했음을 알 수 있다.


##(3)
df %>%
filter(year == 2020 & month == 2 & day > 15 & day < 30 )%>%
group_by(prov) %>%
summarise(confirm = sum(cases))
##대구에서 가장 많이 발생했음을 알 수 있다.
```



###5번

```{r}
##(1)
cumprod(c(7,6,5,4,3,2,1))

##(2)


##(3)
library(tidyverse)
random = rnorm(1000) 
random = as_tibble(random)
colnames(random) = c('P1')
random %>% filter(P1>0) %>% count

##(4)
rbinom(1000,size=1, prob=0.2) %>% mean
#약 200개가 포함된다는 것을 알 수 있다.

##(5)
y_5 = rnorm(5000,1,1)
hist(y_5)

##(6)
x_6 = -1000:1000/1000
sum_4=0
for(i in 1:1000){
sum_4= sum_4 + x_6[2*i]
}
print(sum_4)

##(7)

##(8)
calculate = function(x){
if(x>0){
return(log(x))
}else{
if(x==0){
print("음의 무한대")
}else{
print("x는 양수이어야 합니다.")
}
}
}

##(9)
df=tibble(X1=rnorm(100),X2=rnorm(100))
head(df)
df %>% mutate(Z=(X1^2+X2^2))

##(10)
```



##6번
```{r}

##(2)
corrider = rep(FALSE,100)
open <- function(x) !x
open[(1:100) %% 2 ==0] %>% open

##(4)
MAT = rbind(c(1,2,3,4),c(2,2,1,0), c(0,1,-1,0), c(3,1,-1,3))
MAT_1 = c(1,9,4,7)
dim(MAT_1)=c(4,1)
solve(MAT) %*% MAT_1
##답은 w=2 x=3, y=-1, z=-1 가 된다.
```