```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("dplyr")
#install.packages("tidyverse")
library(dplyr)
library(tidyverse)
```

\newpage

### 1번
```{r}
y = c()
t = c()
for (i in 1:1000){
  t[i] = (2*pi*i)/1000
  y[i] = 1.5+(5*sin(t[i]))+(3*cos(4*t[i]))
}
```

```{r}
epsilon = rnorm(1000,mean=0,sd=1)
y = y+epsilon
```

```{r}
x_1 = c()
x_2 = c()
for (i in 1:1000){
  x_1[i] = sin(t[i])
  x_2[i] = cos(4*t[i])
}
```

* * *

```{r}
for (i in 1:1000){
  y[i] = 1.5+(5*x_1[i])+(3*x_2[i])
}
y = y+epsilon
plot(t,y,col='gray60')
```

* * *

```{r}
X = cbind(1,x_1,x_2)
head(X)
```

* * *

```{r}
beta = rbind(1.5,5,3)
rslt = X %*% beta

for (i in 1:1000){
  y[i] = 1.5+(5*x_1[i])+(3*x_2[i])
}
y = y+epsilon
plot(t,y,col='gray60')
lines(t,rslt,col='red',lwd=5)
```

* * *

```{r}
betahat = solve(t(X) %*% X) %*% t(X) %*% y
print(beta)
print(betahat)
```

* * *

```{r}
rslt_ = X %*% betahat
plot(t,y,col='gray60')
lines(t,rslt,col='red',lwd=5)
lines(t,rslt_,col='blue',lty=2,lwd=5)
```

\newpage


### 2번

```{r}
x=seq(from=-1.96,to=1.96,by=0.01)
y=(1/sqrt(2*pi))*exp(-1/2*x^2)
xx = runif(10000, -2, 2)
yy = runif(10000, 0.05, 0.4)
plot(xx,yy)
lines(x,y,col='red',lwd=5)
```

* * *

```{r}
test = function(xx,yy) {
  yy < (1/sqrt(2*pi))*exp(-1/2*xx^2)
}
tst = c()
for (i in 1:10000) tst[i] = test(xx[i],yy[i])
plot(xx,yy,col='gray')
lines(x,y,col='red',lwd=5)
points(xx[tst],yy[tst],col='red')
```

* * *

```{r}
print(sum(tst))
sum(tst)/10000 * 4 * 0.35 #넓이
```

```{r}
a = rnorm(1000,mean=0,sd=1)
head(a)
```

```{r}
aa = (a[a > -1.96 & a < 1.96])
length(aa)
```

* * *

### 3번

```{r}
#type A
ARR = c('N1','N2','N3','N4','N5','N6','N7','N8','A','N9')
SURV = 10
PLAYER = ARR[SURV]
STAGE = 0
tossRSLT = NA

reset = function(){
SURV <<- 10
STAGE <<- 0
PLAYER <<- ARR[SURV]
tossRSLT <<- NA
}
toss = function(p) rbinom(n=1, size=1, prob=p) %>% as.logical
```

* * *

```{r}
go = function(){
  for (i in 1:20){
    PROB = 0.5+(PLAYER=='A')*0.45
    tossRSLT <<- toss(PROB)
    if (tossRSLT == FALSE) SURV <<- SURV-1
    STAGE <<- STAGE + 1
    PLAYER <<- ARR[SURV]
    if (SURV == 0) break
  }
}
simulate_once = function(){
  reset()
  go()
  return(record()$SURV)
}
record = function(){
  list(SURV=SURV, STAGE=STAGE)
  }

surv8 = 0
```

* * *

```{r}
for (i in 1:10000){
  reset()
  go()
  record()
  if (record()$SURV > 7) surv8 <<- surv8 + 1
}

print(surv8/10000)
```

* * *

```{r}
#type B
ARR = c('N9','A','N8','N7','N6','N5','N4','N3','N2','N1')
SURV <<- 10
PLAYER <<- ARR[SURV]
STAGE <<- 0
tossRSLT <<- NA
surv8 <<- 0

for (i in 1:10000){
  reset()
  go()
  record()
  if (record()$SURV <= 3) surv8 <<- surv8 + 1
}

print(surv8/10000)
```

* * *

### 4번

```{r}
df=read_csv('https://raw.githubusercontent.com/guebin/2021IR/master/_notebooks/covid19.csv')
head(df)
```

* * *

```{r}
df %>% group_by(year) %>% summarize(sum=sum(cases))
```

* * *

```{r}
df %>% group_by(prov) %>% filter(year==2020, month==2, day<=15) %>% summarize(sum=sum(cases))
```

* * *

```{r}
df %>% group_by(prov) %>% filter(year==2020, month==2, day>15) %>% summarize(sum=sum(cases))
```
